language: python
python:
  - "2.7"
#  - "3.2"
env:
  - DJANGO_VERSION=1.4
install:
  - pip install -q -r requirements.txt
  - pip install -q -I Django==$DJANGO_VERSION
  - pip install -q tox
  - python setup.py -q install
script:
  - python setup.py test
